name: Launch Go
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.20'
      - run: go run hello.go Bonjour le monde